config/routes.rb
Rails.application.routes.draw do


   #管理者
  get '/admin', to: 'admin/homes#top'
  devise_for :admins
  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :items, except:[:destroy]
    resources :genres, only:[:index, :edit, :create, :update]
  end

  #会員
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  devise_for :customers , controllers: { registrations: 'customers/registrations' }

  scope module: :public do
    resources :customers, only:[:edit, :update] do
      collection do
        get :my_page
        get :unsubscribe
        delete :withdraw
      end
    end
    resources :orders, only:[:index, :create, :show, :new] do
      collection do
       post :confirm
       get :complete
      end
    end

    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show]

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/customer.rb
class Customer < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :current_password
  has_many :addresses
  has_many :cart_items
  has_many :order

  validates :is_deleted, inclusion: { in: [true, false] }

  # 物理削除の代わりにユーザーの`deleted_at`をタイムスタンプで更新
  def soft_delete
    update_attribute(:is_deleted, Time.current)
  end

  # ユーザーのアカウントが有効であることを確認
  def active_for_authentication?
    super && !is_deleted
  end

  # 削除したユーザーにカスタムメッセージを追加します
  def inactive_message
    !is_deleted ? super : :deleted_account
  end


  with_options presence: true do
    validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, :email

    with_options numericality: { allow_nil: true } do
      validates :postal_code, :phone_number
    end


    # with_options length: { minimum: 6 } do
    #   validates :password
    # end

  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "successfully."
    else
      render "show"
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :is_deleted )
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  #editでパスワードを入力しないで済むために必要
  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end

  #update後に好きな画面にリダイレクトするメソッド
    def after_update_path_for(_resource)
      my_page_customers_path
    end

     # DELETE /resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h3><mark><%= @customer.last_name %><%= @customer.first_name %> さん　の会員情報編集</mark></h3>

   <%= form_with model: @customer, url:admin_customer_path(@customer), local:true do |f| %>
     <table class="table table-borderless">
       <div class="field">
        <%= f.label :id, "会員ID"%>
        <%= @customer.id %>
       </div>

  　  　 <div class="field">
        <%= f.label :name, '氏名' %>
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
       </div>
       </div>

       <div class="field">
        <%= f.label :name_kana, 'フリガナ' %>
        <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %><%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
       </div>

       <div class="field">
        <%= f.label :postal_code, '郵便番号' %>
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
       </div>

       <div class="field">
        <%= f.label :adress, '住所' %>
        <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
       </div>

       <div class="field">
        <%= f.label :phone_number, '電話番号' %>
        <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number" %>
       </div>

       <div class="field">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
       </div>

       <div>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "有効", {value: :true, style: "display: inline-block;"} %>
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "無効", {value: :false, style: "display: inline-block;"} %>
        <!--%= f.radio_button :is_active, :[['有効',0],['無効',1]], { include_blank: true, selected: 0 } %>-->

        <div class="actions">
         <%= f.submit "変更を保存する" ,class: 'btn btn-success' %>
        </div>
       </div>
    </table>
   <% end %>
</div>

app/views/admin/customers/index.html.erb
<h3><mark>会員一覧</mark></h3>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
     <% @customers.each do |customer|%>
    <tr>
      <td>
        <p><%= customer.id %></p>
      </td>
      <td>
           <%= link_to admin_customer_path(customer.id), class: "show_page" do %>
             <%= customer.last_name %><%= customer.first_name %>
           <% end %>
      </td>
      <td>
        <p><%= customer.email %></p>
      </td>
      <td>
        <p><%= customer.is_deleted == true ? "退会済" : "有効" %></p>
      </td>
    </tr>
      <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h3><mark><%= @customer.last_name %> <%= @customer.first_name %>さんの会員詳細</mark></h3>
    <!--<div class="pull-right">-->
    <!--  %=link_to "", new_admin_item_path, class: "glyphicon glyphicon-plus-sign add_icon "%>-->
    <!--</div>-->
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>顧客ID</th>
          <th>氏名</th>
          <th>フリガナ</th>
          <th>郵便番号</th>
          <th>住所</th>
          <th>電話番号</th>
          <th>メールアドレス</th>
        </tr>
      </thead>
      <tbody>
          <%= form_with model: @customer, local:true do |customer| %>
        <tr>
          <td>
            <p><%= @customer.id %> <%= @customer.is_deleted == true ? "無効会員" : "有効会員" %></p>
          </td>
          <td>
            <p><%= @customer.last_name %><%= @customer.first_name %></p>
          </td>
          <td>
            <p><%= @customer.last_name_kana %><%= @customer.first_name_kana %></p>
          </td>
          <td>
            <p><%= @customer.postal_code %></p>
          </td>
          <td>
            <p><%= @customer.address %></p>
          </td>
          <td>
            <p><%= @customer.phone_number %></p>
          </td>
          <td>
            <p><%= @customer.email %></p>
          </td>
        </tr>
          <% end %>
      </tbody>
    </table>

   　　 <div><%= link_to '編集する', edit_admin_customer_path(@customer), class: "btn-sm btn-success" %></div>
     　<div><%= link_to '注文履歴一覧をみる',  edit_admin_customer_path(@customer),  class: "btn-sm btn-danger" %></div>
      </tr>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>