config/routes.rb
Rails.application.routes.draw do


   #管理者
  get '/admin', to: 'admin/homes#top'
  devise_for :admins
  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :items, except:[:destroy]
    resources :genres, only:[:index, :edit, :create, :update]
  end

  #会員
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  devise_for :customers , controllers: { registrations: 'customers/registrations' }

  scope module: :public do
    resources :customers, only:[:edit, :update] do
      collection do
        get :my_page
        get :unsubscribe
        delete :withdraw
      end
    end
    resources :orders, only:[:index, :create, :show, :new] do
      collection do
       post :confirm
       get :complete
      end
    end

    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show]

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items
  # def self.admin_id
  # end
  validates :name, presence: true
  validates :is_active, inclusion: { in: [true, false] }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    # @genre.admin_id = current_admin.id

    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre), notice: "You have updated address successfully."
    else
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:is_active, :genre_id, :name )
  end


end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class='row'>
  <h3><mark>ジャンル編集</mark></h3>

<%= form_with model: @genre, url:admin_genre_path, local: true do |f| %>
    <%= f.label "ジャンル" %><%= f.text_field :name %>

    <%= f.radio_button :is_active, :true %>
    <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
    <%= f.radio_button :is_active, :false %>
    <%= f.label :is_active, "無効", {value: :false, style: "display: inline-block;"} %>


    <%= f.submit "変更を保存する" , class: "btn-sm btn-success" %>
<% end %>

 </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
<div class='row'>
<h3><mark>ジャンル一覧・追加</mark></h3>

<%= form_with model: @genre, url:admin_genres_path, local: true do |f| %>

    <%= f.label "ジャンル" %><%= f.text_field :name %>

    <%= f.radio_button :is_active, :true %>
    <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
    <%= f.radio_button :is_active, :false %>
    <%= f.label :is_active, "無効", {value: :false, style: "display: inline-block;"} %>

    <%= f.submit "追加" , class: "btn-sm btn-success " %>
<% end %>


 <tbody>
  <table class="table table-striped">
  <!--<table class="table table-hover table-inverse">-->
       <thead>
        <tr>
          <th>ジャンル</th>
          <th>状態</th>
          <th>　</th>
        </tr>
       </thead>

    <% @genres.each do |genre| %>
     <tr>
      <td>
       <p><%= genre.name %></p>
      </td>
      <td>
       <p><%= genre.is_active == true ? "有効" : "無効" %></p>
      </td>
      <td class=>
       　  <%= link_to '編集する' ,edit_admin_genre_path(genre), class: "btn btn-primary" %>
      </td>
     </tr>
   <% end %>
   </table>
  </tbody>
 </table>
</div>
</div>