config/routes.rb
Rails.application.routes.draw do


   #管理者
  get '/admin', to: 'admin/homes#top'
  devise_for :admins
  namespace :admin do
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :items, except:[:destroy]
    resources :genres, only:[:index, :edit, :create, :update]
  end

  #会員
  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'

  devise_for :customers , controllers: { registrations: 'customers/registrations' }

  scope module: :public do
    resources :customers, only:[:edit, :update] do
      collection do
        get :my_page
        get :unsubscribe
        delete :withdraw
      end
    end
    resources :orders, only:[:index, :create, :show, :new] do
      collection do
       post :confirm
       get :complete
      end
    end

    resources :cart_items, only:[:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :items, only:[:index, :show]

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def view_name
    '(' + self.postal_code.to_s + ')' + self.address + self.name
  end

  # include JpPrefecture
  # jp_prefecture :prefecture_code

  # def prefecture_name
  #   JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  # end

  # def prefecture_name=(prefecture_name)
  #   self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  # end

  with_options presence: true  do
    validates :address, :name

    with_options numericality: { allow_nil: true } do
      validates :postal_code
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  validates :amount, numericality: true

  # validates :amount,
  #   numericality:{ only_integer: true, greater_than: 1}
end

app/models/customer.rb
class Customer < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :current_password
  has_many :addresses
  has_many :cart_items
  has_many :order

  validates :is_deleted, inclusion: { in: [true, false] }

  # 物理削除の代わりにユーザーの`deleted_at`をタイムスタンプで更新
  def soft_delete
    update_attribute(:is_deleted, Time.current)
  end

  # ユーザーのアカウントが有効であることを確認
  def active_for_authentication?
    super && !is_deleted
  end

  # 削除したユーザーにカスタムメッセージを追加します
  def inactive_message
    !is_deleted ? super : :deleted_account
  end


  with_options presence: true do
    validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, :email

    with_options numericality: { allow_nil: true } do
      validates :postal_code, :phone_number
    end


    # with_options length: { minimum: 6 } do
    #   validates :password
    # end

  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items
  # def self.admin_id
  # end
  validates :name, presence: true
  validates :is_active, inclusion: { in: [true, false] }

end

app/models/item.rb
class Item < ApplicationRecord


 attachment :image
 belongs_to :genre
 has_many :cart_items
 has_many :oder_items



 # validates :is_active, inclusion: {in: [true, false]}
 validates :name, :price, :introduction, presence: true
 validates :price, numericality: true

# validates :is_active, inclusion: { in: %w(draft publish private) }

end

app/models/order.rb
class Order < ApplicationRecord

  enum method_pay:{クレジットカード: 0,銀行振込:1}
  enum status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

  belongs_to :customer
  # has_many :cart_items
  has_many :order_items

  def sum_of_price
    order_sum + shipping
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum production_status:{制作不可: 0, 制作待ち: 1, 製作中: 2, 制作完了: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    # @genre.admin_id = current_admin.id

    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre), notice: "You have updated address successfully."
    else
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:is_active, :genre_id, :name )
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render 'edit'
    end
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render 'new'
    end
  end

  private
  def item_params

    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # deviseコントローラーにストロングパラメータを追加する
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <!--%= csrf_meta_tags %>-->
    <%= csp_meta_tag %>
    <%= csrf_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="back-color">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
       <div class="logo navbar-left">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png' ,:size =>'150x60' %>
          <% end %>
       </div>
      <ul class="nav pull-right nav-pills header-botton">
      <% if customer_signed_in? %>
      　<li>ようこそ<%= current_customer.first_name_kana %>さん！
        <li><%= link_to ' マイページ', my_page_customers_path, class: "btn btn-primary" %></li>
        <li><%= link_to ' 商品一覧', items_path, class: "btn btn-success" %></li>
        <li><%= link_to ' カート', cart_items_path, class: "btn btn-info" %></li>
        <li><%= link_to ' ログアウト', destroy_customer_session_path, method: :delete, "data-confirm" => "ログアウトしますか？", class: "btn btn-danger" %></li>
      <% elsif admin_signed_in? %>
        <li><%= link_to ' 商品一覧', admin_items_path, class: "btn btn-primary" %></li>
        <li><%= link_to ' 会員一覧', admin_customers_path, class: "btn btn-success" %></li>
        <li><%= link_to ' 注文履歴一覧', admin_orders_path, class: "btn btn-info" %></li>
        <li><%= link_to ' ジャンル一覧', admin_genres_path, class: "btn btn-warning" %></li>
        <li><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete, "data-confirm" => "ログアウトしますか？", class: "btn btn-danger" %></li>
      <% else %>
        <li><%= link_to ' About', about_path, class: "btn btn-primary" %></li>
        <li><%= link_to ' 商品一覧', items_path, class: "btn btn-success" %></li>
        <li><%= link_to ' 新規登録', new_customer_registration_path, class: "btn btn-warning" %></li>
        <li><%= link_to ' ログイン', new_customer_session_path, class: "btn btn-danger" %></li>
      <% end %>
      </ul>
    </header>

    <div class="container body-down">
      <div class="row">
        <%= yield %>
      </div>
    </div>

    <footer>
    </footer>
  </body>
</html>